#!/usr/bin/bash
# ---------------------------------------------------------
# Color pick that works outside terminal
# using yad and xclip.
# ---------------------------------------------------------
# Prerequisites: bash, yad, xclip
# 	Instalation: apply execution permission by chmod +x colorpick and then move  
#                      the file to your /usr/local/bin directory.
#	  How to use: just type 'colorpick' from terminal.  
#   How it works: It uses the yad to pop up a color picker window.  
#	             You can type the choosen color from hex format #303030  
#                 or click on the color drop icon to choose the desired color  
#	             from the web and the picked color will be automaticaly copyied to  
#                 the clipboard.  
# ---------------------------------------------------------
# Author: Rômulo Pinheiro
# Creation: 24/03/2021
#	version: 1.0
# License: GPL
# ---------------------------------------------------------


TITLE="Color Picker"
ICON="gtk-color-picker"

color=$(yad --window-icon=$ICON --title="$TITLE" --color)

xclip -selection clipboard <<< $color
